/**
 * Team Adapter
 * 
 * Converts between CrmTeam (API model) and User (UI model)
 */

import { CrmTeam, CrmTeamRequest } from '@/types/crmApi';
import { User } from '@/types';

/**
 * Convert CrmTeam to User
 */
export function crmTeamToUser(crmTeam: CrmTeam): User {
  if (!crmTeam || !crmTeam.id) {
    throw new Error('Invalid CrmTeam: missing id');
  }

  // Parse additional_info if it's a JSON string
  let parsedAdditionalInfo: any = {};
  if (crmTeam.additional_info) {
    try {
      parsedAdditionalInfo = typeof crmTeam.additional_info === 'string'
        ? JSON.parse(crmTeam.additional_info)
        : crmTeam.additional_info;
    } catch {
      // If parsing fails, use empty object
      parsedAdditionalInfo = {};
    }
  }

  // Map role from API to UI role
  let uiRole: 'admin' | 'doctor' | 'staff' = 'staff';
  if (crmTeam.role) {
    const roleLower = crmTeam.role.toLowerCase();
    if (roleLower === 'admin' || roleLower === 'administrator') {
      uiRole = 'admin';
    } else if (roleLower === 'doctor' || roleLower === 'physician' || roleLower === 'dr') {
      uiRole = 'doctor';
    } else {
      uiRole = 'staff';
    }
  }

  // Map status from API to UI status
  let uiStatus: 'active' | 'OnLeave' | 'inactive' = 'inactive';
  if (crmTeam.status) {
    const statusLower = crmTeam.status.toLowerCase();
    if (statusLower === 'active') {
      uiStatus = 'active';
    } else if (statusLower === 'leave' || statusLower === 'on leave' || statusLower === 'onleave') {
      uiStatus = 'OnLeave';
    } else {
      uiStatus = 'inactive';
    }
  }

  // Generate initials from name
  const generateInitials = (name: string): string => {
    if (!name) return 'U';
    const names = name.trim().split(' ').filter(n => n.length > 0);
    if (names.length === 0) return 'U';
    if (names.length === 1) return names[0].charAt(0).toUpperCase();
    return (names[0].charAt(0) + names[names.length - 1].charAt(0)).toUpperCase();
  };

  return {
    id: crmTeam.id,
    name: crmTeam.name || '',
    email: parsedAdditionalInfo.email || '',
    role: uiRole,
    department: parsedAdditionalInfo.department || crmTeam.role || '',
    specialization: parsedAdditionalInfo.specialization || '',
    experience: parsedAdditionalInfo.experience || '',
    phone: parsedAdditionalInfo.phone || '',
    status: uiStatus,
    initials: generateInitials(crmTeam.name),
    avatarColor: undefined, // Will be generated by UI
    rating: parsedAdditionalInfo.rating,
    appointmentCount: parsedAdditionalInfo.appointmentCount,
    createdAt: crmTeam.created_at ? new Date(crmTeam.created_at) : undefined,
    updatedAt: crmTeam.updated_at ? new Date(crmTeam.updated_at) : undefined,
  };
}

/**
 * Convert User to CrmTeamRequest
 */
export function userToCrmTeam(user: Partial<User> & { name: string }): CrmTeamRequest {
  // Build additional_info object from User fields
  const additionalInfo: any = {};
  
  if (user.email) additionalInfo.email = user.email;
  if (user.phone) additionalInfo.phone = user.phone;
  if (user.department) additionalInfo.department = user.department;
  if (user.specialization) additionalInfo.specialization = user.specialization;
  if (user.experience) additionalInfo.experience = user.experience;
  if (user.rating) additionalInfo.rating = user.rating;
  if (user.appointmentCount !== undefined) additionalInfo.appointmentCount = user.appointmentCount;

  // Map UI role to API role
  let apiRole = user.role || 'staff';
  
  // Map UI status to API status
  // Convert 'OnLeave' to 'onleave' for API compatibility
  let apiStatus: string = user.status || 'inactive';
  if (apiStatus === 'OnLeave') {
    apiStatus = 'onleave';
  }

  return {
    name: user.name,
    org_id: undefined, // Will be set by backend if needed
    role: apiRole,
    status: apiStatus,
    // Send as JSON object, not stringified - backend expects map[string]interface{}
    additional_info: Object.keys(additionalInfo).length > 0 ? additionalInfo : undefined,
  };
}

/**
 * Convert array of CrmTeam to array of User
 */
export function crmTeamsToUsers(teams: CrmTeam[] | null | undefined): User[] {
  if (!teams || !Array.isArray(teams)) {
    return [];
  }

  return teams
    .filter((team): team is CrmTeam => {
      return team !== null && team !== undefined && typeof team === 'object' && !!team.id;
    })
    .map((team) => {
      try {
        return crmTeamToUser(team);
      } catch (error) {
        console.error('Error converting CrmTeam to User:', error, team);
        return null;
      }
    })
    .filter((user): user is User => user !== null);
}

